name: Appium Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  appium-tests:
    runs-on: ubuntu-latest
    env:
      UDID: ${{ secrets.UDID }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install
